=== mc-cip/spec/json_schema/project.schema.json
{
  "$id": "project.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "MODIP Metadata Format - Project",
  "type": "object",
  "additionalProperties": false,
  "definitions": {
    "author": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name"
      ],
      "properties": {
        "id": {
          "type": "string",
          "description": "A unique identifier of this author."
        },
        "name": {
          "type": "string",
          "description": "A human-readable name of this author"
        },
        "uri": {
          "type": "string",
          "description": "A URI users can visit to view more about this author.",
          "format": "uri"
        }
      }
    }
  },
  "required": [
    "schemaVersion",
    "id",
    "name"
  ],
  "properties": {
    "$schema": true,
    "schemaVersion": {
      "type": "integer",
      "description": "The version of the MODIP Metadata Format.",
      "minimum": 1,
      "maximum": 1
    },
    "id": {
      "type": "string",
      "description": "A unique identifier for this Project."
    },
    "name": {
      "type": "string",
      "description": "The human-readable name of this Project."
    },
    "summary": {
      "type": "string",
      "description": "A short summary of this project, without HTML."
    },
    "description": {
      "type": "string",
      "description": "A long description of this project. May contain HTML."
    },
    "media": {
      "type": "array",
      "description": "Media Items for this Project.",
      "items": {
        "type": "object",
        "description": "A Media Item.",
        "additionalProperties": false,
        "properties": {
          "rel": {
            "type": "string",
            "description": "Relation of this Media Item.",
            "enum": [
              "icon",
              "gallery"
            ]
          },
          "type": {
            "type": "string",
            "description": "The type of this Media Item.",
            "enum": [
              "image",
              "video"
            ]
          },
          "src": {
            "type": "string",
            "description": "The source of this Media Item.",
            "format": "uri"
          },
          "caption": {
            "type": "string",
            "description": "A caption for this Media Item. Cannot contain HTML."
          },
          "sha256": {
            "type": "string",
            "description": "An SHA256 hash of the item linked to in src. Conflicts with embed."
          },
          "embed": {
            "type": "string",
            "description": "A link to an embedded webpage. Conflicts with sha256 and src.",
            "format": "uri"
          }
        },
        "oneOf": [
          {
            "properties": {
              "embed": false
            },
            "required": [
              "src",
              "rel",
              "type"
            ]
          },
          {
            "properties": {
              "sha256": false,
              "src": false
            },
            "required": [
              "rel",
              "type",
              "embed"
            ]
          }
        ]
      }
    },
    "authors": {
      "type": "array",
      "description": "The authors of this Project.",
      "items": {
        "oneOf": [
          {
            "type": "object",
            "description": "An individual author.",
            "$ref": "#/definitions/author"
          },
          {
            "type": "object",
            "description": "A Team consisting of multiple authors.",
            "additionalProperties": false,
            "required": [
              "team",
              "id",
              "name",
              "members"
            ],
            "properties": {
              "team": {
                "const": true,
                "description": "Indicates whether or not this is a Team. Must be 'true' for Teams."
              },
              "id": {
                "type": "string",
                "description": "A unique identifier of this Team."
              },
              "name": {
                "type": "string",
                "description": "A human-readable name of this Team."
              },
              "uri": {
                "type": "string",
                "description": "A URI users can visit to view more about this Team.",
                "format": "uri"
              },
              "members": {
                "type": "array",
                "description": "A list of authors that are part of this t Team.",
                "items": {
                  "$ref": "#/definitions/author"
                }
              }
            }
          }
        ]
      }
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "string",
        "description": "A tag that can be used to categorize this Project.",
        "examples": [
          "mod",
          "modpack",
          "resourcepack",
          "datapack",
          "world",
          "framework"
        ]
      }
    },
    "license": {
      "type": "object",
      "description": "License Information for this Project.",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "uri"
      ],
      "properties": {
        "id": {
          "type": "string",
          "description": "An identifier for this license. Includes all SPDX identifiers, as well as ARR, MMPL, Generic-Open, and Generic-Proprietary."
        },
        "name": {
          "type": "string",
          "description": "A human-readable name of this license."
        },
        "uri": {
          "type": "string",
          "description": "A URI where the full text of this license can be viewed.",
          "format": "uri"
        },
        "modpackUsage": {
          "type": "string",
          "description": "Information on whether this Project can be used in modpacks.",
          "enum": [
            "alwaysAllow",
            "requiresPermission",
            "neverAllow"
          ]
        }
      }
    },
    "links": {
      "type": "array",
      "description": "A list of links relating to this Project.",
      "items": {
        "type": "object",
        "description": "A Link Object related to the Project.",
        "required": [
          "rel",
          "name",
          "uri"
        ],
        "properties": {
          "rel": {
            "oneOf": [
              {
                "type": "string"
              },
              {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            ],
            "description": "The relation of this Link to the Project. Can be an array.",
            "examples": [
              "homepage",
              "documentation",
              "wiki",
              "scm",
              "issues",
              "community"
            ]
          },
          "name": {
            "type": "string",
            "description": "A human-readable name of this Link."
          },
          "uri": {
            "type": "string",
            "description": "The Link, which can be viewed in a web browser.",
            "format": "uri"
          }
        }
      }
    },
    "successor": {
      "oneOf": [
        {
          "type": "string"
        },
        {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      ],
      "description": "A successor mod ID."
    },
    "predecessor": {
      "oneOf": [
        {
          "type": "string"
        },
        {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      ],
      "description": "A predecessor mod ID."
    },
    "versions": {
      "type": "array",
      "description": "Version information for this Project.",
      "items": {
        "$ref": "./version.schema.json"
      }
    }
  }
}

=== mc-cip/spec/examples/format_example.json
{
  "$schema": "../json_schema/project.schema.json",
  "schemaVersion": 1,
  "id": "111111-111111-111111-111111-111111",
  "name": "Example Project",
  "summary": "This is a short, one-sentence summary of the Example Project.",
  "description": "This is a long description describing the project. <b>HTML</b> can optionally be used.",
  "media": [
    {
      "rel": "icon",
      "type": "image",
      "src": "https://example.com/example.png",
      "sha256": "< sum goes here >"
    },
    {
      "rel": "gallery",
      "type": "video",
      "embed": "https://youtube.com/embed...",
      "caption": "This is an example embed."
    },
    {
      "rel": "gallery",
      "type": "video",
      "src": "https://example.com/video.webm",
      "caption": "This is an example direct video link.",
      "sha256": "< sum goes here >"
    },
    {
      "rel": "gallery",
      "type": "image",
      "src": "https://example.com/image.png",
      "caption": "This is an example image."
    }
  ],
  "authors": [
    {
      "team": true,
      "id": "111111-111111-111111-111111-111111",
      "name": "MODIP Contributors",
      "uri": "https://github.com/mc-cip",
      "members": [
        {
          "id": "111111-111111-111111-111111-111111",
          "name": "Example MODIP Member",
          "uri": "https://example.com/example-webpage"
        }
      ]
    }
  ],
  "tags": [
    "mod"
  ],
  "license": {
    "id": "MIT",
    "name": "MIT",
    "uri": "https://opensource.org/licenses/MIT",
    "modpackUsage": "alwaysAllow"
  },
  "links": [
    {
      "rel": [
        "x-discord",
        "community"
      ],
      "name": "Project Discord",
      "uri": "https://discord.gg/example"
    },
    {
      "rel": "scm",
      "name": "Project GitHub",
      "uri": "https://github.com/mc-cip/exampleproject"
    }
  ],
  "successor": [
    "successor-mod",
    "other-successor-mod"
  ],
  "predecessor": "predecessor-mod",
  "versions": [
    {
      "id": "1.0.0",
      "name": "Release 1.0.0",
      "semver": "1.0.0",
      "releaseDate": "2020-04-08T12:00:00Z",
      "changelog": "Example changelog goes here... <b>HTML</b> may be used.",
      "dependencies": [
        {
          "id": "minecraft",
          "version": [
            "1.16.1",
            "1.16"
          ]
        },
        {
          "src": "https://example.com/external-modip-metadata.json",
          "id": "example-library-mod",
          "required": true,
          "version": [
            "1.0.0",
            "1.0.1"
          ]
        }
      ],
      "files": [
        {
          "rel": "primary",
          "name": "1.0.0-fabric.jar",
          "sha256": "< sum goes here >",
          "dependencies": [
            {
              "id": "framework-fabric-loader",
              "required": true,
              "version": ">= 0.6.1.45"
            }
          ],
          "installation": {
            "method": "placeInDirectory",
            "directory": "mods"
          },
          "downloads": [
            "https://example.com/download/1.0.0-fabric.jar"
          ]
        },
        {
          "rel": "primary",
          "name": "1.0.0-forge.jar",
          "sha256": "< sum goes here >",
          "dependencies": [
            {
              "id": "framework-forge",
              "required": true,
              "version": ">= 32.0.106"
            }
          ],
          "installation": {
            "method": "placeInDirectory",
            "directory": "mods"
          },
          "downloads": [
            "https://example.com/download/1.0.0-forge.jar"
          ]
        }
      ]
    }
  ]
}
